### ISSUE TITLE
install befehle in .bat-Datei auslagern

### ISSUE THREAD

**Issue by OnurOezcan** [TaleTime/TaleTime#56]
Die Schritte 2, 3 und 4 in eine .bat-Datei auslagern und jeweils mit "call"
aufrufen.
mit >>2 können dann die Errors in eine Log-Datei geschrieben werden.
So können die gefühlt 20 Installationsschritte automatisiert werden und aus der Log-Datei können in die Warnungen besser eingelesen werden.

**Comment by OnurOezcan** [comment]
Export the steps 2, 3 and 4 into a .bat file and use "call" to start the commands.
with >>2 the errors can be written into a log file.
So the esteemed 20 installation steps can be automated and from the log file the warnings can be read better.

**Comment by SilasScholl** [comment]
TaleTimeInit.bat exists
