### ISSUE TITLE
GitHub Badges:

### ISSUE THREAD

**Issue by amen99** [TaleTime/TaleTime#91]
*- <a href="https://medium.com/better-programming/add-badges-to-a-github-repository-716d2988dc6a">Artikel</a>*
*- <a href="https://github.com/badges/shields">Repo dazu</a>*
*- <a href="https://shields.io/category/build">Build/Test badges</a>*
*- <a href="https://circleci.com/ und https://travis-ci.org/ usw.">Integration</a>*

**Comment by amiede** [comment]
Derzeit sind die Badges hier nur Grafiken, die Logik dahinter fehlt noch, siehe z.B. hier: https://github.com/ForrestKnight/atom
